image: java:8-jdk

stages:
  - build
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew publish
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week

